version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_DB=moj_rozvrh'
    ports:
      - '5432:5432'